# Buat liat distribusi data yang di crop berdasarkan nilai min count yang dipakai

In [1]:
!pip install gensim top2vec

Requirement already satisfied: gensim in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (4.3.0)
Requirement already satisfied: top2vec in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (1.0.36)
Requirement already satisfied: numpy>=1.18.5 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from gensim) (1.26.4)
Requirement already satisfied: scipy>=1.7.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from gensim) (1.11.4)
Requirement already satisfied: smart-open>=1.8.1 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from gensim) (7.1.0)
Requirement already satisfied: FuzzyTM>=0.4.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from gensim) (2.0.9)
Requirement already satisfied: Cython==0.29.32 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from gensim) (0.29.32)
Requirement already satisfied: pandas in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from top2vec) (2.3.3)
Requirement already satisfied: scikit-learn>=1.2.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from top2vec) (1.6.1)
Requirement already satisfied: umap-learn>=0.5.1 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from top2vec) (0.5.11)
Requirement already satisfied: hdbscan>=0.8.27 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from top2vec) (0.8.42)
Requirement already satisfied: wordcloud in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from top2vec) (1.9.6)
Requirement already satisfied: transformers in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from top2vec) (5.5.0)
Requirement already satisfied: tqdm in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from top2vec) (4.67.1)
Requirement already satisfied: pyfume in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from FuzzyTM>=0.4.0->gensim) (0.3.1)
Requirement already satisfied: joblib>=1.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from hdbscan>=0.8.27->top2vec) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from scikit-learn>=1.2.0->top2vec) (3.6.0)
Requirement already satisfied: wrapt in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from smart-open>=1.8.1->gensim) (1.14.1)
Requirement already satisfied: numba>=0.51.2 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from umap-learn>=0.5.1->top2vec) (0.65.0)
Requirement already satisfied: pynndescent>=0.5 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from umap-learn>=0.5.1->top2vec) (0.6.0)
Requirement already satisfied: llvmlite<0.48,>=0.47.0dev0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from numba>=0.51.2->umap-learn>=0.5.1->top2vec) (0.47.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from pandas->top2vec) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from pandas->top2vec) (2022.7.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from pandas->top2vec) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from python-dateutil>=2.8.2->pandas->top2vec) (1.17.0)
Requirement already satisfied: simpful in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from pyfume->FuzzyTM>=0.4.0->gensim) (2.12.0)
Requirement already satisfied: fst-pso in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from pyfume->FuzzyTM>=0.4.0->gensim) (1.8.1)
Requirement already satisfied: typing-extensions in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from pyfume->FuzzyTM>=0.4.0->gensim) (4.13.2)
Requirement already satisfied: miniful in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from fst-pso->pyfume->FuzzyTM>=0.4.0->gensim) (0.0.6)
Requirement already satisfied: colorama in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from tqdm->top2vec) (0.4.6)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from transformers->top2vec) (1.9.0)
Requirement already satisfied: packaging>=20.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from transformers->top2vec) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from transformers->top2vec) (6.0.2)
Requirement already satisfied: regex>=2025.10.22 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from transformers->top2vec) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from transformers->top2vec) (0.22.2)
Requirement already satisfied: typer in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from transformers->top2vec) (0.15.4)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from transformers->top2vec) (0.5.3)
Requirement already satisfied: filelock>=3.10.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (2024.6.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (0.28.1)
Requirement already satisfied: anyio in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (4.12.1)
Requirement already satisfied: certifi in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (2025.4.26)
Requirement already satisfied: httpcore==1.* in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (1.0.9)
Requirement already satisfied: idna in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (3.10)
Requirement already satisfied: h11>=0.16 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (0.16.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (1.2.2)
Requirement already satisfied: click<8.2,>=8.0.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from typer->transformers->top2vec) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from typer->transformers->top2vec) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from typer->transformers->top2vec) (14.0.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from rich>=10.11.0->typer->transformers->top2vec) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from rich>=10.11.0->typer->transformers->top2vec) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->transformers->top2vec) (0.1.2)
Requirement already satisfied: pillow in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from wordcloud->top2vec) (12.1.1)
Requirement already satisfied: matplotlib in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from wordcloud->top2vec) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from matplotlib->wordcloud->top2vec) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from matplotlib->wordcloud->top2vec) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from matplotlib->wordcloud->top2vec) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from matplotlib->wordcloud->top2vec) (1.4.8)
Requirement already satisfied: pyparsing>=3 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from matplotlib->wordcloud->top2vec) (3.2.3)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
from top2vec import Top2Vec
import pandas as pd
from bertopic import BERTopic
from bertopic.backend import MultiModalBackend
from bertopic.representation import KeyBERTInspired
import re
from sklearn.feature_extraction.text import CountVectorizer
from umap import UMAP
from hdbscan import HDBSCAN
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import random
from gensim.models.coherencemodel import CoherenceModel
from gensim.corpora.dictionary import Dictionary

c:\Users\Allen\Documents\Python Env\environments\derp_learning\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
df = pd.read_csv(r"C:\Users\Allen\Documents\GitHub\thesis-research\combined_tweets_dataset\sample_v2\vibe_coding_combined_translated.csv")

In [4]:
df = df[["full_text_translated", "image_url"]]

In [5]:
df.head()

,full_text_translated,image_url
0,@karpathy me vibe coding and hope it can just ...,https://pbs.twimg.com/media/Gi0a82HaQAA97Q-.jpg
1,vibes capital meets vibe coding = greatest eco...,NaN
2,vibe coding https://t.co/1hHVMmunrw,https://pbs.twimg.com/media/Gi0f9fAWgAAgox6.jpg
3,can attest. vibe coding is hella fun and borde...,NaN
4,I have built a few app ideas in my spare time ...,NaN

In [6]:
def preprocess_tweet(text):
    #lower case text
    text = text.lower()
    # Remove URLs
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)
    # Remove user mentions
    text = re.sub(r'@\w+', '', text)
    # Remove hashtags
    text = re.sub(r'#\w+', '', text)
    #remove symbols
    text = re.sub(r'[^\w\s]', '', text)
    #remove numbers
    text = re.sub(r'\d+', '', text)
    #Replace all "vibe code" into vibecode
    text = re.sub(r'vibe code', 'vibecode', text)
    #Replace all "vibe coding" into vibecoding
    text = re.sub(r'vibe coding', 'vibecoding', text)
    #Relace all "vibe coded" into vibecoded
    text = re.sub(r'vibe coded', 'vibecoded', text)
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [7]:
df_preprocessed = df['full_text_translated'].fillna('').apply(preprocess_tweet)
df_preprocessed = pd.concat([df_preprocessed, df['image_url']], axis=1)

In [8]:
df_preprocessed = df_preprocessed[df_preprocessed['full_text_translated'].apply(lambda x: len(x.split()) >= 4)]
df_preprocessed.count()

full_text_translated    20511
image_url                6495
dtype: int64

In [12]:
from collections import Counter
import pandas as pd

# Asumsi df['text'] adalah tweet kamu
all_words = ' '.join(df_preprocessed['full_text_translated']).split()
word_freq = Counter(all_words)

# Lihat berapa banyak kata yang muncul hanya 1-5 kali
freq_df = pd.DataFrame(word_freq.items(), columns=['word', 'count'])
freq_df.head()

         word  count
0          me   1640
1  vibecoding  17566
2         and  11496
3        hope     77
4          it   6401

In [16]:
print(freq_df[freq_df['count'] < 10].shape[0], "kata akan terbuang jika min_count=10")

19873 kata akan terbuang jika min_count=10