# NGRAM = TRUE
# MIN_COUNT = 10
# EMBEDDER = all-MiniLM-L6-v2

In [1]:
!pip install gensim top2vec

Requirement already satisfied: gensim in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (4.3.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: top2vec in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (1.0.36)
Requirement already satisfied: numpy>=1.18.5 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from gensim) (1.26.4)
Requirement already satisfied: scipy>=1.7.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from gensim) (1.11.4)
Requirement already satisfied: smart-open>=1.8.1 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from gensim) (7.1.0)
Requirement already satisfied: FuzzyTM>=0.4.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from gensim) (2.0.9)
Requirement already satisfied: Cython==0.29.32 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from gensim) (0.29.32)
Requirement already satisfied: pandas in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from top2vec) (2.3.3)
Requirement already satisfied: scikit-learn>=1.2.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from top2vec) (1.6.1)
Requirement already satisfied: umap-learn>=0.5.1 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from top2vec) (0.5.11)
Requirement already satisfied: hdbscan>=0.8.27 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from top2vec) (0.8.42)
Requirement already satisfied: wordcloud in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from top2vec) (1.9.6)
Requirement already satisfied: transformers in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from top2vec) (5.5.0)
Requirement already satisfied: tqdm in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from top2vec) (4.67.1)
Requirement already satisfied: pyfume in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from FuzzyTM>=0.4.0->gensim) (0.3.1)
Requirement already satisfied: joblib>=1.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from hdbscan>=0.8.27->top2vec) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from scikit-learn>=1.2.0->top2vec) (3.6.0)
Requirement already satisfied: wrapt in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from smart-open>=1.8.1->gensim) (1.14.1)
Requirement already satisfied: numba>=0.51.2 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from umap-learn>=0.5.1->top2vec) (0.65.0)
Requirement already satisfied: pynndescent>=0.5 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from umap-learn>=0.5.1->top2vec) (0.6.0)
Requirement already satisfied: llvmlite<0.48,>=0.47.0dev0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from numba>=0.51.2->umap-learn>=0.5.1->top2vec) (0.47.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from pandas->top2vec) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from pandas->top2vec) (2022.7.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from pandas->top2vec) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from python-dateutil>=2.8.2->pandas->top2vec) (1.17.0)
Requirement already satisfied: simpful in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from pyfume->FuzzyTM>=0.4.0->gensim) (2.12.0)
Requirement already satisfied: fst-pso in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from pyfume->FuzzyTM>=0.4.0->gensim) (1.8.1)
Requirement already satisfied: typing-extensions in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from pyfume->FuzzyTM>=0.4.0->gensim) (4.13.2)
Requirement already satisfied: miniful in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from fst-pso->pyfume->FuzzyTM>=0.4.0->gensim) (0.0.6)
Requirement already satisfied: colorama in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from tqdm->top2vec) (0.4.6)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from transformers->top2vec) (1.9.0)
Requirement already satisfied: packaging>=20.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from transformers->top2vec) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from transformers->top2vec) (6.0.2)
Requirement already satisfied: regex>=2025.10.22 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from transformers->top2vec) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from transformers->top2vec) (0.22.2)
Requirement already satisfied: typer in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from transformers->top2vec) (0.15.4)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from transformers->top2vec) (0.5.3)
Requirement already satisfied: filelock>=3.10.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (2024.6.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (0.28.1)
Requirement already satisfied: anyio in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (4.12.1)
Requirement already satisfied: certifi in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (2025.4.26)
Requirement already satisfied: httpcore==1.* in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (1.0.9)
Requirement already satisfied: idna in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (3.10)
Requirement already satisfied: h11>=0.16 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (0.16.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (1.2.2)
Requirement already satisfied: click<8.2,>=8.0.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from typer->transformers->top2vec) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from typer->transformers->top2vec) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from typer->transformers->top2vec) (14.0.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from rich>=10.11.0->typer->transformers->top2vec) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from rich>=10.11.0->typer->transformers->top2vec) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->transformers->top2vec) (0.1.2)
Requirement already satisfied: pillow in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from wordcloud->top2vec) (12.1.1)
Requirement already satisfied: matplotlib in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from wordcloud->top2vec) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from matplotlib->wordcloud->top2vec) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from matplotlib->wordcloud->top2vec) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from matplotlib->wordcloud->top2vec) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from matplotlib->wordcloud->top2vec) (1.4.8)
Requirement already satisfied: pyparsing>=3 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from matplotlib->wordcloud->top2vec) (3.2.3)

In [2]:
from top2vec import Top2Vec
import pandas as pd
from bertopic import BERTopic
from bertopic.backend import MultiModalBackend
from bertopic.representation import KeyBERTInspired
import re
from sklearn.feature_extraction.text import CountVectorizer
from umap import UMAP
from hdbscan import HDBSCAN
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import random
from gensim.models.coherencemodel import CoherenceModel
from gensim.corpora.dictionary import Dictionary

c:\Users\Allen\Documents\Python Env\environments\derp_learning\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
df = pd.read_csv(r"C:\Users\Allen\Documents\GitHub\thesis-research\combined_tweets_dataset\sample_v2\vibe_coding_combined_translated.csv")

In [4]:
df = df[["full_text_translated", "image_url"]]

In [5]:
df.head()

,full_text_translated,image_url
0,@karpathy me vibe coding and hope it can just ...,https://pbs.twimg.com/media/Gi0a82HaQAA97Q-.jpg
1,vibes capital meets vibe coding = greatest eco...,NaN
2,vibe coding https://t.co/1hHVMmunrw,https://pbs.twimg.com/media/Gi0f9fAWgAAgox6.jpg
3,can attest. vibe coding is hella fun and borde...,NaN
4,I have built a few app ideas in my spare time ...,NaN

In [6]:
def preprocess_tweet(text):
    #lower case text
    text = text.lower()
    # Remove URLs
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)
    # Remove user mentions
    text = re.sub(r'@\w+', '', text)
    # Remove hashtags
    text = re.sub(r'#\w+', '', text)
    #remove symbols
    text = re.sub(r'[^\w\s]', '', text)
    #remove numbers
    text = re.sub(r'\d+', '', text)
    #Replace all "vibe code" into vibecode
    text = re.sub(r'vibe code', 'vibecode', text)
    #Replace all "vibe coding" into vibecoding
    text = re.sub(r'vibe coding', 'vibecoding', text)
    #Relace all "vibe coded" into vibecoded
    text = re.sub(r'vibe coded', 'vibecoded', text)
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [7]:
df_preprocessed = df['full_text_translated'].fillna('').apply(preprocess_tweet)
df_preprocessed = pd.concat([df_preprocessed, df['image_url']], axis=1)

In [8]:
df_preprocessed = df_preprocessed[df_preprocessed['full_text_translated'].apply(lambda x: len(x.split()) >= 4)]
df_preprocessed.count()

full_text_translated    20511
image_url                6495
dtype: int64

In [9]:
docs = df_preprocessed['full_text_translated'].tolist()
images  = df_preprocessed['image_url'].tolist()
for i in range(len(images)):
    if pd.isna(images[i]):
        images[i] = None
random.shuffle(docs)
docs[:10]

['kalshi taking k out of peoples accounts because they cant vibecode their rewards system right lmaooo',
 'anyone heard of this claude thing i think it could be huge you just finance a mac mini and start vibecoding were probably gonna change the world with this one imo if you havent tried it you definitely should but tbh if u arent already using claude its probably over for you',
 'its a lot more expensive to vibecode software or hire software engineers who can use ai the state of outsourcing software engineering to ai or vibecoders is about the same as the state of outsourcing medical treatment to ai and yes many idiots do believe that ai gt mds',
 'also why everyone started vibecoding during last weeks what happened exactly can someone tell the news or maybe therre is something in the water now',
 'so much vibecoding and so little vibe pming',
 'vibecoding art i made with cursor and photoshop used cursor to make python script that detects contours and generates boxes around them left part and makes random fractals corresponding to the size of those boxes',
 'just to let you know is not just a product launch the roadmap includes multichain expansion communitybuilt games prediction markets and a decentralized gaming economy hbet is central to every stage of growth',
 'a free guide on vibecoding with claude your aipowered development accelerator',
 'torvalds says he briefly used ai for a hobby project reinforcing pragmatic limits skepticism toward hype and caution around critical software development',
 'if you consider yourself an earnest progressive intellectual but dont recognise the reactionary dehumanisation campaign targeted against million people that will only fuel more violence amp war while destroying the information ecosystem then i have no respect for you at all']

In [10]:
# embedding_model = SentenceTransformer("all-mpnet-base-v2")

umap_model = UMAP(n_neighbors=10, n_components=5, min_dist=0.0)
hdbscan_model = HDBSCAN(min_cluster_size=15, min_samples=1)
vectorizer_model = CountVectorizer(
    stop_words="english",
    ngram_range=(1, 2),
    max_df=0.8,
    min_df=2
)

representation_model = KeyBERTInspired()

In [11]:
# Top2Vec topic modeling
documents = [doc for doc in docs if isinstance(doc, str) and doc.strip()]
tokenized_documents = [doc.split() for doc in documents]

dictionary = Dictionary(tokenized_documents)
dictionary.filter_extremes(no_below=2, no_above=0.5)

print(f"tokenized documents: {tokenized_documents[:5]}")
print(f"Number of documents: {len(documents)}")
print(f"Number of unique tokens: {len(dictionary)}")

tokenized documents: [['kalshi', 'taking', 'k', 'out', 'of', 'peoples', 'accounts', 'because', 'they', 'cant', 'vibecode', 'their', 'rewards', 'system', 'right', 'lmaooo'], ['anyone', 'heard', 'of', 'this', 'claude', 'thing', 'i', 'think', 'it', 'could', 'be', 'huge', 'you', 'just', 'finance', 'a', 'mac', 'mini', 'and', 'start', 'vibecoding', 'were', 'probably', 'gonna', 'change', 'the', 'world', 'with', 'this', 'one', 'imo', 'if', 'you', 'havent', 'tried', 'it', 'you', 'definitely', 'should', 'but', 'tbh', 'if', 'u', 'arent', 'already', 'using', 'claude', 'its', 'probably', 'over', 'for', 'you'], ['its', 'a', 'lot', 'more', 'expensive', 'to', 'vibecode', 'software', 'or', 'hire', 'software', 'engineers', 'who', 'can', 'use', 'ai', 'the', 'state', 'of', 'outsourcing', 'software', 'engineering', 'to', 'ai', 'or', 'vibecoders', 'is', 'about', 'the', 'same', 'as', 'the', 'state', 'of', 'outsourcing', 'medical', 'treatment', 'to', 'ai', 'and', 'yes', 'many', 'idiots', 'do', 'believe', 'that', 'ai', 'gt', 'mds'], ['also', 'why', 'everyone', 'started', 'vibecoding', 'during', 'last', 'weeks', 'what', 'happened', 'exactly', 'can', 'someone', 'tell', 'the', 'news', 'or', 'maybe', 'therre', 'is', 'something', 'in', 'the', 'water', 'now'], ['so', 'much', 'vibecoding', 'and', 'so', 'little', 'vibe', 'pming']]
Number of documents: 20511
Number of unique tokens: 11348

In [12]:
print(dictionary.token2id)

{'accounts': 0, 'because': 1, 'cant': 2, 'k': 3, 'kalshi': 4, 'lmaooo': 5, 'of': 6, 'out': 7, 'peoples': 8, 'rewards': 9, 'right': 10, 'system': 11, 'taking': 12, 'their': 13, 'they': 14, 'vibecode': 15, 'a': 16, 'already': 17, 'and': 18, 'anyone': 19, 'arent': 20, 'be': 21, 'but': 22, 'change': 23, 'claude': 24, 'could': 25, 'definitely': 26, 'finance': 27, 'for': 28, 'gonna': 29, 'havent': 30, 'heard': 31, 'huge': 32, 'i': 33, 'if': 34, 'imo': 35, 'it': 36, 'its': 37, 'just': 38, 'mac': 39, 'mini': 40, 'one': 41, 'over': 42, 'probably': 43, 'should': 44, 'start': 45, 'tbh': 46, 'thing': 47, 'think': 48, 'this': 49, 'tried': 50, 'u': 51, 'using': 52, 'were': 53, 'with': 54, 'world': 55, 'you': 56, 'about': 57, 'ai': 58, 'as': 59, 'believe': 60, 'can': 61, 'do': 62, 'engineering': 63, 'engineers': 64, 'expensive': 65, 'gt': 66, 'hire': 67, 'idiots': 68, 'is': 69, 'lot': 70, 'many': 71, 'medical': 72, 'more': 73, 'or': 74, 'outsourcing': 75, 'same': 76, 'software': 77, 'state': 78, 'that': 79, 'to': 80, 'treatment': 81, 'use': 82, 'vibecoders': 83, 'who': 84, 'yes': 85, 'also': 86, 'during': 87, 'everyone': 88, 'exactly': 89, 'happened': 90, 'in': 91, 'last': 92, 'maybe': 93, 'news': 94, 'now': 95, 'someone': 96, 'something': 97, 'started': 98, 'tell': 99, 'water': 100, 'weeks': 101, 'what': 102, 'why': 103, 'little': 104, 'much': 105, 'pming': 106, 'so': 107, 'vibe': 108, 'around': 109, 'art': 110, 'boxes': 111, 'corresponding': 112, 'cursor': 113, 'fractals': 114, 'generates': 115, 'left': 116, 'made': 117, 'make': 118, 'makes': 119, 'part': 120, 'photoshop': 121, 'python': 122, 'random': 123, 'script': 124, 'size': 125, 'them': 126, 'those': 127, 'used': 128, 'central': 129, 'decentralized': 130, 'economy': 131, 'every': 132, 'expansion': 133, 'games': 134, 'gaming': 135, 'growth': 136, 'includes': 137, 'know': 138, 'launch': 139, 'let': 140, 'markets': 141, 'multichain': 142, 'not': 143, 'prediction': 144, 'product': 145, 'roadmap': 146, 'stage': 147, 'accelerator': 148, 'aipowered': 149, 'development': 150, 'free': 151, 'guide': 152, 'on': 153, 'your': 154, 'briefly': 155, 'caution': 156, 'critical': 157, 'he': 158, 'hobby': 159, 'hype': 160, 'limits': 161, 'pragmatic': 162, 'project': 163, 'says': 164, 'skepticism': 165, 'torvalds': 166, 'toward': 167, 'against': 168, 'all': 169, 'amp': 170, 'an': 171, 'at': 172, 'campaign': 173, 'consider': 174, 'destroying': 175, 'dont': 176, 'earnest': 177, 'ecosystem': 178, 'fuel': 179, 'have': 180, 'information': 181, 'intellectual': 182, 'million': 183, 'no': 184, 'only': 185, 'people': 186, 'progressive': 187, 'reactionary': 188, 'recognise': 189, 'respect': 190, 'targeted': 191, 'then': 192, 'violence': 193, 'war': 194, 'while': 195, 'will': 196, 'yourself': 197, 'airdrop': 198, 'butts': 199, 'by': 200, 'cats': 201, 'ct': 202, 'dogs': 203, 'endless': 204, 'fair': 205, 'flywheel': 206, 'frogs': 207, 'funding': 208, 'great': 209, 'here': 210, 'im': 211, 'initiative': 212, 'legit': 213, 'like': 214, 'looks': 215, 'magic': 216, 'mcp': 217, 'meta': 218, 'next': 219, 'other': 220, 'shitcoins': 221, 'sick': 222, 'sparking': 223, 'vibecoin': 224, 'level': 225, 'linux': 226, 'are': 227, 'been': 228, 'code': 229, 'couple': 230, 'dictation': 231, 'hours': 232, 'how': 233, 'ive': 234, 'need': 235, 'nextlevel': 236, 'past': 237, 'powers': 238, 'super': 239, 'typing': 240, 'up': 241, 'wake': 242, 'without': 243, 'writing': 244, 'hackathon': 245, 'our': 246, 'contract': 247, 'cool': 248, 'smart': 249, 'became': 250, 'bigger': 251, 'feel': 252, 'us': 253, 'uses': 254, 'bridge': 255, 'chicken': 256, 'cookin': 257, 'cooking': 258, 'crew': 259, 'down': 260, 'from': 261, 'got': 262, 'hot': 263, 'ideas': 264, 'isnt': 265, 'laying': 266, 'learning': 267, 'leveraging': 268, 'serious': 269, 'some': 270, 'spicy': 271, 'team': 272, 'theyre': 273, 'today': 274, 'treated': 275, 'coffee': 276, 'current': 277, 'income': 278, 'passive': 279, 'aicoding': 280, 'area': 281, 'bay': 282, 'dev': 283, 'devin': 284, 'efficiency': 285, 'faster': 286, 'follow': 287, 'hitting': 288, 'hows': 289, 'prompt': 290, 'startups': 291, 'tips': 292, 'tools': 293, 'tweak': 294, 'write': 295, 'x': 296, 'under': 297, 'branches': 298, 'codes': 299, 'different': 300, 'levelup': 301, 'two': 302, 'app': 303, 'basic': 304, 'basically': 305, 'build': 306, 'building': 307, 'good': 308, 'hut': 309, 'knowhow': 310, 'log': 311, 'own': 312, 'physical': 313, 'similar': 314, 'structure': 315, 'me': 316, 'twitch': 317, 'watch': 318, 'any': 319, 'important': 320, 'practical': 321, 'workplace': 322, 'gemini': 323, 'model': 324, 'most': 325, 'operations': 326, 'pro': 327, 'problems': 328, 'small': 329, 'sonnet': 330, 'survey': 331, 'which': 332, 'agent': 333, 'agentic': 334, 'apps': 335, 'builds': 336, 'create': 337, 'documents': 338, 'execute': 339, 'first': 340, 'insert': 341, 'inside': 342, 'integration': 343, 'into': 344, 'introducing': 345, 'platform': 346, 'search': 347, 'single': 348, 'web': 349, 'bb': 350, 'coloring': 351, 'database': 352, 'db': 353, 'generate': 354, 'hack': 355, 'member': 356, 'messing': 357, 'page': 358, 'setup': 359, 'take': 360, 'vibecoded': 361, 'working': 362, 'am': 363, 'blind': 364, 'fan': 365, 'feeling': 366, 'hate': 367, 'lets': 368, 'moving': 369, 'problem': 370, 'say': 371, 'somethings': 372, 'spent': 373, 'through': 374, 'wanna': 375, 'week': 376, 'work': 377, 'linkedin': 378, 'put': 379, 'skill': 380, 'ass': 381, 'mf': 382, 'seriously': 383, 'youre': 384, 'amount': 385, 'aqua': 386, 'become': 387, 'bus': 388, 'costco': 389, 'developed': 390, 'family': 391, 'farming': 392, 'fishing': 393, 'grandfathers': 394, 'has': 395, 'kisarazu': 396, 'land': 397, 'line': 398, 'money': 399, 'my': 400, 'owns': 401, 'plan': 402, 'scary': 403, 'seems': 404, 'story': 405, 'terminal': 406, 'thanks': 407, 'was': 408, 'where': 409, 'clipping': 410, 'age': 411, 'descriptions': 412, 'look': 413, 'pr': 414, 'away': 415, 'blog': 416, 'changer': 417, 'companys': 418, 'desk': 419, 'even': 420, 'figured': 421, 'forward': 422, 'game': 423, 'iphone': 424, 'projects': 425, 'push': 426, 'since': 427, 'when': 428, 'wrote': 429, 'copilot': 430, 'incredible': 431, 'ordering': 432, 'stock': 433, 'vscode': 434, 'wifes': 435, 'live': 436, 'w': 437, 'based': 438, 'correct': 439, 'encountered': 440, 'experiences': 441, 'following': 442, 'gave': 443, 'generative': 444, 'held': 445, 'interact': 446, 'knowledge': 447, 'lt': 448, 'meeting': 449, 'presentations': 450, 'services': 451, 'shared': 452, 'themes': 453, 'three': 454, 'time': 455, 'took': 456, 'way': 457, 'we': 458, 'yesterday': 459, '①': 460, '②': 461, '③': 462, 'cap': 463, 'founders': 464, 'getting': 465, 'squatting': 466, 'table': 467, 'api': 468, 'built': 469, 'custom': 470, 'models': 471, 'off': 472, 'scratching': 473, 'shelf': 474, 'si': 475, 'surface': 476, 'value': 477, 'clubfor': 478, 'consumptionmusic': 479, 'dance': 480, 'dreamy': 481, 'visuals': 482, 'weirdo': 483, 'agents': 484, 'come': 485, 'dm': 486, 'hosting': 487, 'sunday': 488, 'these': 489, 'want': 490, 'buddy': 491, 'charts': 492, 'constantly': 493, 'crash': 494, 'deal': 495, 'duol': 496, 'get': 497, 'happens': 498, 'himself': 499, 'keep': 500, 'languages': 501, 'multiple': 502, 'once': 503, 'paying': 504, 'posting': 505, 'question': 506, 'revenue': 507, 'whats': 508, 'always': 509, 'betting': 510, 'business': 511, 'crypto': 512, 'gets': 513, 'ground': 514, 'making': 515, 'shoot': 516, 'sports': 517, 'whatever': 518, 'youve': 519, 'boost': 520, 'bootcamp': 521, 'chat': 522, 'cli': 523, 'frontend': 524, 'git': 525, 'github': 526, 'html': 527, 'installation': 528, 'node': 529, 'testing': 530, 'too': 531, 'vibey': 532, 'claudesonnetthinking': 533, 'coding': 534, 'everything': 535, 'admins': 536, 'applications': 537, 'complex': 538, 'decent': 539, 'gatekeeping': 540, 'junk': 541, 'majority': 542, 'nonprogrammers': 543, 'program': 544, 'really': 545, 'rhetoric': 546, 'truly': 547, 'wonder': 548, 'pivot': 549, 'qa': 550, 'fascinating': 551, 'loveable': 552, 'thatll': 553, 'does': 554, 'doing': 555, 'fuck': 556, 'guys': 557, 'humble': 558, 'love': 559, 'man': 560, 'shit': 561, 'sorry': 562, 'supporting': 563, 'whole': 564, 'ago': 565, 'chill': 566, 'confident': 567, 'confused': 568, 'cup': 569, 'did': 570, 'didnt': 571, 'few': 572, 'gm': 573, 'headphones': 574, 'late': 575, 'listening': 576, 'music': 577, 'night': 578, 'sometimes': 579, 'thats': 580, 'though': 581, 'wearing': 582, 'years': 583, 'approved': 584, 'carefully': 585, 'changes': 586, 'diffs': 587, 'eager': 588, 'experienced': 589, 'giving': 590, 'human': 591, 'intern': 592, 'lead': 593, 'proposed': 594, 'reviewed': 595, 'tech': 596, 'ultimately': 597, 'wrong': 598, 'almost': 599, 'bro': 600, 'stop': 601, 'anything': 602, 'chain': 603, 'codexero': 604, 'difficult': 605, 'enjoy': 606, 'fun': 607, 'hard': 608, 'input': 609, 'learn': 610, 'new': 611, 'process': 612, 'simply': 613, 'thoughts': 614, 'youd': 615, 'accidentally': 616, 'quick': 617, 'task': 618, 'trying': 619, 'bugs': 620, 'cleanup': 621, 'creating': 622, 'deployment': 623, 'dread': 624, 'easy': 625, 'engineer': 626, 'finds': 627, 'fix': 628, 'handle': 629, 'hit': 630, 'kills': 631, 'legacy': 632, 'messy': 633, 'rules': 634, 'store': 635, 'stuff': 636, 'day': 637, 'delve': 638, 'emotions': 639, 'exact': 640, 'feedback': 641, 'loop': 642, 'mad': 643, 'marketing': 644, 'psychology': 645, 'scientist': 646, 'solving': 647, 'decided': 648, 'finally': 649, 'goes': 650, 'join': 651, 'see': 652, 'sprites': 653, 'beating': 654, 'billion': 655, 'companies': 656, 'dismissing': 657, 'dying': 658, 'grip': 659, 'losing': 660, 'microsoft': 661, 'multi': 662, 'pushing': 663, 'regrets': 664, 'salesforce': 665, 'slop': 666, 'winning': 667, 'automatically': 668, 'backend': 669, 'dashboard': 670, 'entire': 671, 'foundry': 672, 'front': 673, 'handles': 674, 'individually': 675, 'llm': 676, 'mean': 677, 'meaning': 678, 'ontology': 679, 'originally': 680, 'scratch': 681, 'sdk': 682, 'set': 683, 'stack': 684, 'userfriendly': 685, 'usually': 686, 'debug': 687, 'until': 688, 'big': 689, 'care': 690, 'company': 691, 'find': 692, 'honestly': 693, 'interesting': 694, 'leveling': 695, 'life': 696, 'real': 697, 'run': 698, 'theres': 699, 'addition': 700, 'below': 701, 'bolt': 702, 'bunch': 703, 'challenge': 704, 'chance': 705, 'credits': 706, 'design': 707, 'full': 708, 'instructions': 709, 'monday': 710, 'prize': 711, 'running': 712, 'short': 713, 'try': 714, 'accessible': 715, 'asking': 716, 'creation': 717, 'exciting': 718, 'experience': 719, 'language': 720, 'natural': 721, 'partnered': 722, 'regardless': 723, 'revolutionary': 724, 'embracing': 725, 'exploring': 726, 'latest': 727, 'silicon': 728, 'trend': 729, 'valleys': 730, 'useful': 731, 'bear': 732, 'case': 733, 'lil': 734, 'morning': 735, 'review': 736, 'saturday': 737, 'claud': 738, 'desire': 739, 'educational': 740, 'grateful': 741, 'js': 742, 'positioning': 743, 'site': 744, 'situation': 745, 'stumble': 746, 'thank': 747, 'understand': 748, 'wondering': 749, 'beyond': 750, 'capital': 751, 'fresh': 752, 'going': 753, 'help': 754, 'metal': 755, 'startup': 756, 'actual': 757, 'aspects': 758, 'bit': 759, 'itself': 760, 'syntax': 761, 'works': 762, 'era': 763, 'forgot': 764, 'punk': 765, 'rick': 766, 'rock': 767, 'solana': 768, 'admit': 769, 'asset': 770, 'comment': 771, 'complete': 772, 'ill': 773, 'max': 774, 'media': 775, 'send': 776, 'ship': 777, 'together': 778, 'tweet': 779, 'actually': 780, 'decade': 781, 'hes': 782, 'his': 783, 'knows': 784, 'lens': 785, 'might': 786, 'shipping': 787, 'things': 788, 'viewed': 789, 'both': 790, 'bucks': 791, 'distribution': 792, 'headsdown': 793, 'however': 794, 'marketers': 795, 'mission': 796, 'net': 797, 'products': 798, 'reach': 799, 'struggling': 800, 'superpowers': 801, 'worth': 802, 'choosing': 803, 'newsletter': 804, 'ok': 805, 'parts': 806, 'setting': 807, 'there': 808, 'addiction': 809, 'base': 810, 'crowdfund': 811, 'facility': 812, 'group': 813, 'health': 814, 'mental': 815, 'miniapp': 816, 'tba': 817, 'begins': 818, 'consistent': 819, 'cost': 820, 'executes': 821, 'idea': 822, 'low': 823, 'reliably': 824, 'speed': 825, 'stays': 826, 'supports': 827, 'name': 828, 'realized': 829, 'vibecoder': 830, 'sleep': 831, 'soon': 832, 'anymore': 833, 'chances': 834, 'developer': 835, 'effective': 836, 'hammer': 837, 'less': 838, 'parallel': 839, 'plenty': 840, 'than': 841, 'tool': 842, 'youll': 843, 'budget': 844, 'cs': 845, 'degree': 846, 'interviewers': 847, 'pm': 848, 'technical': 849, 'yea': 850, 'yeah': 851, 'skills': 852, 'social': 853, 'consequences': 854, 'ever': 855, 'had': 856, 'mode': 857, 'created': 858, 'doodle': 859, 'heres': 860, 'inspired': 861, 'jump': 862, 'jumped': 863, 'marathon': 864, 'network': 865, 'og': 866, 'precious': 867, 'steps': 868, 'local': 869, 'lol': 870, 'room': 871, 'venue': 872, 'benchmark': 873, 'endtoend': 874, 'far': 875, 'go': 876, 'production': 877, 'tested': 878, 'actions': 879, 'automate': 880, 'automates': 881, 'defi': 882, 'evolve': 883, 'intelligence': 884, 'learns': 885, 'place': 886, 'platforms': 887, 'quant': 888, 'strategies': 889, 'test': 890, 'enterprise': 891, 'expectations': 892, 'reality': 893, 'teams': 894, 'vs': 895, 'automated': 896, 'center': 897, 'feels': 898, 'flow': 899, 'killing': 900, 'reviews': 901, 'scanning': 902, 'secret': 903, 'secure': 904, 'security': 905, 'talk': 906, 'tests': 907, 'workflows': 908, 'automatic': 909, 'fully': 910, 'gacha': 911, 'machine': 912, 'sense': 913, 'awesome': 914, 'fucking': 915, 'course': 916, 'elden': 917, 'ring': 918, 'available': 919, 'best': 920, 'delivered': 921, 'home': 922, 'merch': 923, 'open': 924, 'opensource': 925, 'participants': 926, 'receive': 927, 'simple': 928, 'source': 929, 'spots': 930, 'track': 931, 'registration': 932, 'old': 933, 's': 934, 'saying': 935, 'update': 936, 'blowing': 937, 'enough': 938, 'mind': 939, 'payloads': 940, 'present': 941, 'safeguards': 942, 'unprecedented': 943, 'vulnerabilities': 944, 'witness': 945, 'actionable': 946, 'br': 947, 'designed': 948, 'handson': 949, 'plans': 950, 'prior': 951, 'sessions': 952, 'solutions': 953, 'turn': 954, 'wants': 955, 'zero': 956, 'behind': 957, 'call': 958, 'details': 959, 'offense': 960, 'personnel': 961, 'publicly': 962, 'another': 963, 'assistant': 964, 'craft': 965, 'eco': 966, 'ended': 967, 'functional': 968, 'later': 969, 'myself': 970, 'research': 971, 'weekend': 972, 'workflow': 973, 'wow': 974, 'across': 975, 'bring': 976, 'continents': 977, 'helping': 978, 'kids': 979, 'anyways': 980, 'figure': 981, 'having': 982, 'humanoid': 983, 'lemme': 984, 'yall': 985, 'edits': 986, 'boomer': 987, 'cute': 988, 'head': 989, 'online': 990, 'sell': 991, 'sound': 992, 'check': 993, 'cloud': 994, 'conversation': 995, 'add': 996, 'cursed': 997, 'drawing': 998, 'future': 999, 'kinda': 1000, 'starts': 1001, 'summoned': 1002, 'typed': 1003, 'curating': 1004, 'fish': 1005, 'teach': 1006, 'estate': 1007, 'instances': 1008, 'laptop': 1009, 'realise': 1010, 'recall': 1011, 'struggle': 1012, 'tab': 1013, 'tabs': 1014, 'terminals': 1015, 'visible': 1016, 'ace': 1017, 'addressing': 1018, 'component': 1019, 'each': 1020, 'groundbreaking': 1021, 'miss': 1022, 'multistep': 1023, 'possibilities': 1024, 'solve': 1025, 'would': 1026, 'authentication': 1027, 'features': 1028, 'mess': 1029, 'minutes': 1030, 'payments': 1031, 'turns': 1032, 'arcade': 1033, 'busy': 1034, 'daily': 1035, 'hasnt': 1036, 'stopped': 1037, 'drop': 1038, 'everybodys': 1039, 'launchpad': 1040, 'attention': 1041, 'audience': 1042, 'begin': 1043, 'brands': 1044, 'coordinating': 1045, 'fans': 1046, 'leverage': 1047, 'likes': 1048, 'post': 1049, 'power': 1050, 'socials': 1051, 'sounds': 1052, 'spam': 1053, 'timeline': 1054, 'bitcoin': 1055, 'coming': 1056, 'financing': 1057, 'infrastructure': 1058, 'successful': 1059, 'wish': 1060, 'balance': 1061, 'finding': 1062, 'specdriven': 1063, 'marketplace': 1064, 'mobile': 1065, 'opportunity': 1066, 'rork': 1067, 'amazing': 1068, 'chatgpt': 1069, 'looking': 1070, 'pure': 1071, 'text': 1072, 'website': 1073, 'jobs': 1074, 'transforming': 1075, 'die': 1076, 'edition': 1077, 'rich': 1078, 'answer': 1079, 'broke': 1080, 'broken': 1081, 'funny': 1082, 'method': 1083, 'mom': 1084, 'never': 1085, 'remember': 1086, 'yo': 1087, 'dancing': 1088, 'audacity': 1089, 'days': 1090, 'favor': 1091, 'somebody': 1092, 'bad': 1093, 'biology': 1094, 'blood': 1095, 'cancer': 1096, 'dangerous': 1097, 'environment': 1098, 'immune': 1099, 'occurrence': 1100, 'operate': 1101, 'perfect': 1102, 'requires': 1103, 'very': 1104, 'wiping': 1105, 'june': 1106, 'singapore': 1107, 'completely': 1108, 'downloads': 1109, 'experiment': 1110, 'month': 1111, 'possible': 1112, 'said': 1113, 'share': 1114, 'success': 1115, 'wanted': 1116, 'well': 1117, 'cube': 1118, 'geometry': 1119, 'hook': 1120, 'textures': 1121, 'upgraded': 1122, 'enjoying': 1123, 'nav': 1124, 'output': 1125, 'side': 1126, 'astro': 1127, 'command': 1128, 'imagine': 1129, 'action': 1130, 'addictive': 1131, 'boring': 1132, 'guess': 1133, 'm': 1134, 'selling': 1135, 'slow': 1136, 'stressful': 1137, 'aigenerated': 1138, 'compliance': 1139, 'creates': 1140, 'enterprises': 1141, 'massive': 1142, 'promises': 1143, 'risks': 1144, 'scale': 1145, 'shadow': 1146, 'threatens': 1147, 'forget': 1148, 'meet': 1149, 'ncs': 1150, 'scene': 1151, 'shaking': 1152, 'viral': 1153, 'googles': 1154, 'leap': 1155, 'powered': 1156, 'prompts': 1157, 'studio': 1158, 'active': 1159, 'dapps': 1160, 'earn': 1161, 'gquack': 1162, 'gxero': 1163, 'lb': 1164, 'missions': 1165, 'still': 1166, 'tracking': 1167, 'xp': 1168, 'able': 1169, 'being': 1170, 'cruise': 1171, 'wifi': 1172, 'after': 1173, 'android': 1174, 'avoided': 1175, 'checking': 1176, 'flutter': 1177, 'general': 1178, 'paid': 1179, 'seeing': 1180, 'tiers': 1181, 'sovereign': 1182, 'welcome': 1183, 'flips': 1184, 'iterating': 1185, 'reverse': 1186, 'specs': 1187, 'strategy': 1188, 'leadership': 1189, 'radar': 1190, 'reasoning': 1191, 'seattle': 1192, 'spatial': 1193, 'training': 1194, 'alone': 1195, 'andrej': 1196, 'describes': 1197, 'early': 1198, 'guiding': 1199, 'karpathy': 1200, 'linebyline': 1201, 'primary': 1202, 'refine': 1203, 'role': 1204, 'shifts': 1205, 'termed': 1206, 'antivibecoding': 1207, 'codebase': 1208, 'hand': 1209, 'manually': 1210, 'must': 1211, 'polish': 1212, 'portions': 1213, 'relearn': 1214, 'cases': 1215, 'failed': 1216, 'feature': 1217, 'implementing': 1218, 'normal': 1219, 'author': 1220, 'between': 1221, 'count': 1222, 'follower': 1223, 'july': 1224, 'teaching': 1225, 'top': 1226, 'vercel': 1227, 'pay': 1228, 'please': 1229, 'everyday': 1230, 'novice': 1231, 'april': 1232, 'austin': 1233, 'session': 1234, 'th': 1235, 'tomorrow': 1236, 'ah': 1237, 'gives': 1238, 'hits': 1239, 'issue': 1240, 'means': 1241, 'nope': 1242, 'opposite': 1243, 'returns': 1244, 'sit': 1245, 'sloppy': 1246, 'empowering': 1247, 'fr': 1248, 'market': 1249, 'nah': 1250, 'study': 1251, 'users': 1252, 'vibing': 1253, 'copypasting': 1254, 'documentation': 1255, 'email': 1256, 'hope': 1257, 'impress': 1258, 'mostly': 1259, 'private': 1260, 'provide': 1261, 'show': 1262, 'upcoming': 1263, 'vacation': 1264, 'wife': 1265, 'aligns': 1266, 'announced': 1267, 'brand': 1268, 'content': 1269, 'existing': 1270, 'gen': 1271, 'leverages': 1272, 'sites': 1273, 'webflow': 1274, 'balls': 1275, 'govt': 1276, 'rage': 1277, 'listen': 1278, 'podcast': 1279, 'advice': 1280, 'bill': 1281, 'gates': 1282, 'lazy': 1283, 'back': 1284, 'files': 1285, 'grok': 1286, 'gtask': 1287, 'gtbe': 1288, 'gtvibecoding': 1289, 'purpose': 1290, 'refactoring': 1291, 'allow': 1292, 'alt': 1293, 'anywhere': 1294, 'ar': 1295, 'considering': 1296, 'dp': 1297, 'g': 1298, 'glasses': 1299, 'inch': 1300, 'screen': 1301, 'smartphone': 1302, 'anthropic': 1303, 'describe': 1304, 'dive': 1305, 'generation': 1306, 'opus': 1307, 'plain': 1308, 'productionready': 1309, 'ready': 1310, 'supercharge': 1311, 'transforms': 1312, 'economic': 1313, 'greatest': 1314, 'lived': 1315, 'lon

In [13]:
import top2vec
print(top2vec.__version__)

1.0.36

In [14]:
top2vec_model = Top2Vec(
    documents=documents,
    ngram_vocab=True,
    min_count=10,
    embedding_model='all-MiniLM-L6-v2',    
    speed='learn',
    workers=2,
    keep_documents=True,
    verbose=True,
 )

topic_words, topic_word_scores, topic_nums = top2vec_model.get_topics()

2026-04-12 15:01:26,379 - top2vec - INFO - Pre-processing documents for training
2026-04-12 15:01:28,034 - top2vec - INFO - Downloading all-MiniLM-L6-v2 model
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6137.51it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-04-12 15:01:33,402 - top2vec - INFO - Creating joint document/word embedding
2026-04-12 15:01:40,773 - top2vec - INFO - Creating lower dimension embedding of documents
2026-04-12 15:01:59,176 - top2vec - INFO - Finding dense areas of documents
2026-04-12 15:02:00,631 - top2vec - INFO - Finding topics

In [15]:
topic_sizes, topic_ids = top2vec_model.get_topic_sizes()
pd.DataFrame({
    "topic_id": topic_ids,
    "size": topic_sizes
}).sort_values("size", ascending=False).head(10)

   topic_id   size
0         0  20036
1         1    256
2         2    219

In [16]:
print(len(topic_sizes))

3

In [18]:
# Coherence metrics for Top2Vec topics (C_V and NPMI)
topic_pairs = []
for topic_num, topic in zip(topic_nums, topic_words):
    cleaned_topic_terms = []
    for term in topic[:10]:
        # ngram terms like "vibe coding" are split so they can be matched to dictionary tokens
        for tok in str(term).split():
            if tok in dictionary.token2id:
                cleaned_topic_terms.append(tok)
    # keep token order, drop duplicates
    cleaned_topic_terms = list(dict.fromkeys(cleaned_topic_terms))
    if len(cleaned_topic_terms) >= 2:
        topic_pairs.append((topic_num, cleaned_topic_terms))

topics_for_coherence = [words for _, words in topic_pairs]
topic_nums_for_coherence = [topic_num for topic_num, _ in topic_pairs]

if not topics_for_coherence:
    raise ValueError("No valid topics left for coherence calculation. Try lowering dictionary filtering or increasing topic words.")

coherence_cv_model = CoherenceModel(
    topics=topics_for_coherence,
    texts=tokenized_documents,
    dictionary=dictionary,
    coherence='c_v',
)

coherence_npmi_model = CoherenceModel(
    topics=topics_for_coherence,
    texts=tokenized_documents,
    dictionary=dictionary,
    coherence='c_npmi',
)

coherence_cv = coherence_cv_model.get_coherence()
coherence_npmi = coherence_npmi_model.get_coherence()

print(f"Total topics used for coherence: {len(topics_for_coherence)}")
print(f"C_V coherence: {coherence_cv:.4f}")
print(f"NPMI coherence: {coherence_npmi:.4f}")

topic_coherence = pd.DataFrame({
    'topic_num': topic_nums_for_coherence,
    'topic_words': [' '.join(words) for words in topics_for_coherence],
    'c_v': coherence_cv_model.get_coherence_per_topic(),
    'npmi': coherence_npmi_model.get_coherence_per_topic(),
})

topic_coherence.sort_values('c_v', ascending=False).head(10)

Total topics used for coherence: 3
C_V coherence: 0.4127
NPMI coherence: -0.2463

,topic_num,topic_words,c_v,npmi
1,1,dance clubfor vibecode camp vibe designing vib...,0.488107,-0.303005
2,2,rust workshop vibecoded projects vibecode camp...,0.393847,-0.246998
0,0,vibecoded projects vibe engineering designing ...,0.356129,-0.188880

In [24]:
topic_words_values = topic_coherence.sort_values('c_v', ascending=False).head(10)['topic_words'].values
print(topic_words_values)

['dance clubfor vibecode camp vibe designing vibecoded projects dreamy weirdo indie hackers punk rock living agentforce vibes investing'
 'rust workshop vibecoded projects vibecode camp vibe engineering debugging designing trading cleanup ltcodinggt investing'
 'vibecoded projects vibe engineering designing marketing debugging vibecode camp investing trading ltcodinggt cleanup']

In [23]:
# Save model
top2vec_model.save("top2vec_ngram_c10.model")

# Load model (di masa depan)
# from top2vec import Top2Vec
top2vec_model = Top2Vec.load("top2vec_ngram_c10.model")



# Load di kemudian hari
# embeddings = np.load("top2vec_ngram_c10_embeddings.npy")


# Simpan Dictionary
dictionary.save("top2vec_ngram_c10.dict")

# Simpan tokenized_documents (menggunakan pickle karena list of lists)
import pickle
with open("top2vec_ngram_c10_tokenized_docs.pkl", "wb") as f:
    pickle.dump(tokenized_documents, f)
    
    
    
# Simpan ringkasan topik dan metriknya
topic_coherence.to_csv("top2vec_ngram_c10_metrics_summary.csv", index=False)

# Simpan representasi topik (10 kata teratas)
top_words_df = pd.DataFrame(topic_words)
top_words_df.to_csv("top2vec_ngram_c10_topic_words.csv")