# CONTEXTUAL EMBEDDING = TRUE
# NGRAM = TRUE
# MIN_COUNT = 10
# EMBEDDER = all-MiniLM-L6-v2

In [1]:
!pip install gensim top2vec

Requirement already satisfied: gensim in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (4.3.0)
Requirement already satisfied: top2vec in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (1.0.36)
Requirement already satisfied: numpy>=1.18.5 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from gensim) (1.26.4)
Requirement already satisfied: scipy>=1.7.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from gensim) (1.11.4)
Requirement already satisfied: smart-open>=1.8.1 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from gensim) (7.1.0)
Requirement already satisfied: FuzzyTM>=0.4.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from gensim) (2.0.9)
Requirement already satisfied: Cython==0.29.32 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from gensim) (0.29.32)
Requirement already satisfied: pandas in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from top2vec) (2.3.3)
Requirement already satisfied: scikit-learn>=1.2.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from top2vec) (1.6.1)
Requirement already satisfied: umap-learn>=0.5.1 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from top2vec) (0.5.11)
Requirement already satisfied: hdbscan>=0.8.27 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from top2vec) (0.8.42)
Requirement already satisfied: wordcloud in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from top2vec) (1.9.6)
Requirement already satisfied: transformers in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from top2vec) (5.5.0)
Requirement already satisfied: tqdm in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from top2vec) (4.67.1)
Requirement already satisfied: pyfume in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from FuzzyTM>=0.4.0->gensim) (0.3.1)
Requirement already satisfied: joblib>=1.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from hdbscan>=0.8.27->top2vec) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from scikit-learn>=1.2.0->top2vec) (3.6.0)
Requirement already satisfied: wrapt in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from smart-open>=1.8.1->gensim) (1.14.1)
Requirement already satisfied: numba>=0.51.2 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from umap-learn>=0.5.1->top2vec) (0.65.0)
Requirement already satisfied: pynndescent>=0.5 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from umap-learn>=0.5.1->top2vec) (0.6.0)
Requirement already satisfied: llvmlite<0.48,>=0.47.0dev0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from numba>=0.51.2->umap-learn>=0.5.1->top2vec) (0.47.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from pandas->top2vec) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from pandas->top2vec) (2022.7.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from pandas->top2vec) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from python-dateutil>=2.8.2->pandas->top2vec) (1.17.0)
Requirement already satisfied: simpful in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from pyfume->FuzzyTM>=0.4.0->gensim) (2.12.0)
Requirement already satisfied: fst-pso in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from pyfume->FuzzyTM>=0.4.0->gensim) (1.8.1)
Requirement already satisfied: typing-extensions in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from pyfume->FuzzyTM>=0.4.0->gensim) (4.13.2)
Requirement already satisfied: miniful in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from fst-pso->pyfume->FuzzyTM>=0.4.0->gensim) (0.0.6)
Requirement already satisfied: colorama in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from tqdm->top2vec) (0.4.6)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from transformers->top2vec) (1.9.0)
Requirement already satisfied: packaging>=20.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from transformers->top2vec) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from transformers->top2vec) (6.0.2)
Requirement already satisfied: regex>=2025.10.22 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from transformers->top2vec) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from transformers->top2vec) (0.22.2)
Requirement already satisfied: typer in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from transformers->top2vec) (0.15.4)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from transformers->top2vec) (0.5.3)
Requirement already satisfied: filelock>=3.10.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (2024.6.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (0.28.1)
Requirement already satisfied: anyio in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (4.12.1)
Requirement already satisfied: certifi in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (2025.4.26)
Requirement already satisfied: httpcore==1.* in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (1.0.9)
Requirement already satisfied: idna in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (3.10)
Requirement already satisfied: h11>=0.16 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (0.16.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers->top2vec) (1.2.2)
Requirement already satisfied: click<8.2,>=8.0.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from typer->transformers->top2vec) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from typer->transformers->top2vec) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from typer->transformers->top2vec) (14.0.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from rich>=10.11.0->typer->transformers->top2vec) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from rich>=10.11.0->typer->transformers->top2vec) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->transformers->top2vec) (0.1.2)
Requirement already satisfied: pillow in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from wordcloud->top2vec) (12.1.1)
Requirement already satisfied: matplotlib in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from wordcloud->top2vec) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from matplotlib->wordcloud->top2vec) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from matplotlib->wordcloud->top2vec) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from matplotlib->wordcloud->top2vec) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from matplotlib->wordcloud->top2vec) (1.4.8)
Requirement already satisfied: pyparsing>=3 in c:\users\allen\documents\python env\environments\derp_learning\lib\site-packages (from matplotlib->wordcloud->top2vec) (3.2.3)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
from top2vec import Top2Vec
import pandas as pd
from bertopic import BERTopic
from bertopic.backend import MultiModalBackend
from bertopic.representation import KeyBERTInspired
import re
from sklearn.feature_extraction.text import CountVectorizer
from umap import UMAP
from hdbscan import HDBSCAN
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import random
from gensim.models.coherencemodel import CoherenceModel
from gensim.corpora.dictionary import Dictionary

c:\Users\Allen\Documents\Python Env\environments\derp_learning\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
df = pd.read_csv(r"C:\Users\Allen\Documents\GitHub\thesis-research\combined_tweets_dataset\sample_v2\vibe_coding_combined_translated.csv")

In [4]:
df = df[["full_text_translated", "image_url"]]

In [5]:
df.head()

,full_text_translated,image_url
0,@karpathy me vibe coding and hope it can just ...,https://pbs.twimg.com/media/Gi0a82HaQAA97Q-.jpg
1,vibes capital meets vibe coding = greatest eco...,NaN
2,vibe coding https://t.co/1hHVMmunrw,https://pbs.twimg.com/media/Gi0f9fAWgAAgox6.jpg
3,can attest. vibe coding is hella fun and borde...,NaN
4,I have built a few app ideas in my spare time ...,NaN

In [6]:
def preprocess_tweet(text):
    #lower case text
    text = text.lower()
    # Remove URLs
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)
    # Remove user mentions
    text = re.sub(r'@\w+', '', text)
    # Remove hashtags
    text = re.sub(r'#\w+', '', text)
    #remove symbols
    text = re.sub(r'[^\w\s]', '', text)
    #remove numbers
    text = re.sub(r'\d+', '', text)
    #Replace all "vibe code" into vibecode
    text = re.sub(r'vibe code', 'vibecode', text)
    #Replace all "vibe coding" into vibecoding
    text = re.sub(r'vibe coding', 'vibecoding', text)
    #Relace all "vibe coded" into vibecoded
    text = re.sub(r'vibe coded', 'vibecoded', text)
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [7]:
df_preprocessed = df['full_text_translated'].fillna('').apply(preprocess_tweet)
df_preprocessed = pd.concat([df_preprocessed, df['image_url']], axis=1)

In [8]:
df_preprocessed = df_preprocessed[df_preprocessed['full_text_translated'].apply(lambda x: len(x.split()) >= 4)]
df_preprocessed.count()

full_text_translated    20511
image_url                6495
dtype: int64

In [9]:
docs = df_preprocessed['full_text_translated'].tolist()
images  = df_preprocessed['image_url'].tolist()
for i in range(len(images)):
    if pd.isna(images[i]):
        images[i] = None
random.shuffle(docs)
docs[:10]

['just built the goal aligner a complete aipowered productivity tool using only vibecoding gemini api integration pdf generation smart goal alignment educational frameworks try it free',
 'may i intorduce ctclicker i created a small crypto twitter based clicker game its not my usual utility tool it was a vibecode practice run for me but maybe some of you enjoy to play a bit',
 'vibecoding with the squad',
 'vibecoding today so i can collect residual income tomorrow while im relaxing on the beach i cant share the full idea yet but i can say this im building a fully autonomous business that runs itself the future looks exciting and im all in',
 'a big reason i want to do a vibecoding app challenge ive been in marketing roles my whole career but ive never shipped and marketed a product of my own ive generated millions of views thousands of users and millions of dollars for businesses kinda wanna see if i can',
 'from a private exchange in re the article about the vibecoding boombust',
 'plena will soon become the home of trading launching and building onchain were unleashing the power of ai to supercharge ecosystems like with builders who can effortlessly create value apps products and contracts vibecode but do it onchain with plena',
 'i was vibecoding last night to build an x clone for specific community i am not sure building a non game is considered vibecoding but with the right level of tech knowledge to configure basic infra code repo servers databases you can basically build anything',
 'openai goes allin on vibecoding says mature experiences are on the horizon',
 'hello from rainy moscow']

In [10]:
# embedding_model = SentenceTransformer("all-mpnet-base-v2")

umap_model = UMAP(n_neighbors=10, n_components=5, min_dist=0.0)
hdbscan_model = HDBSCAN(min_cluster_size=15, min_samples=1)
vectorizer_model = CountVectorizer(
    stop_words="english",
    ngram_range=(1, 2),
    max_df=0.8,
    min_df=2
)

representation_model = KeyBERTInspired()

In [11]:
# Top2Vec topic modeling
documents = [doc for doc in docs if isinstance(doc, str) and doc.strip()]
tokenized_documents = [doc.split() for doc in documents]

dictionary = Dictionary(tokenized_documents)
dictionary.filter_extremes(no_below=2, no_above=0.5)

print(f"tokenized documents: {tokenized_documents[:5]}")
print(f"Number of documents: {len(documents)}")
print(f"Number of unique tokens: {len(dictionary)}")

tokenized documents: [['just', 'built', 'the', 'goal', 'aligner', 'a', 'complete', 'aipowered', 'productivity', 'tool', 'using', 'only', 'vibecoding', 'gemini', 'api', 'integration', 'pdf', 'generation', 'smart', 'goal', 'alignment', 'educational', 'frameworks', 'try', 'it', 'free'], ['may', 'i', 'intorduce', 'ctclicker', 'i', 'created', 'a', 'small', 'crypto', 'twitter', 'based', 'clicker', 'game', 'its', 'not', 'my', 'usual', 'utility', 'tool', 'it', 'was', 'a', 'vibecode', 'practice', 'run', 'for', 'me', 'but', 'maybe', 'some', 'of', 'you', 'enjoy', 'to', 'play', 'a', 'bit'], ['vibecoding', 'with', 'the', 'squad'], ['vibecoding', 'today', 'so', 'i', 'can', 'collect', 'residual', 'income', 'tomorrow', 'while', 'im', 'relaxing', 'on', 'the', 'beach', 'i', 'cant', 'share', 'the', 'full', 'idea', 'yet', 'but', 'i', 'can', 'say', 'this', 'im', 'building', 'a', 'fully', 'autonomous', 'business', 'that', 'runs', 'itself', 'the', 'future', 'looks', 'exciting', 'and', 'im', 'all', 'in'], ['a', 'big', 'reason', 'i', 'want', 'to', 'do', 'a', 'vibecoding', 'app', 'challenge', 'ive', 'been', 'in', 'marketing', 'roles', 'my', 'whole', 'career', 'but', 'ive', 'never', 'shipped', 'and', 'marketed', 'a', 'product', 'of', 'my', 'own', 'ive', 'generated', 'millions', 'of', 'views', 'thousands', 'of', 'users', 'and', 'millions', 'of', 'dollars', 'for', 'businesses', 'kinda', 'wanna', 'see', 'if', 'i', 'can']]
Number of documents: 20511
Number of unique tokens: 11348

In [12]:
print(dictionary.token2id)

{'a': 0, 'aipowered': 1, 'alignment': 2, 'api': 3, 'built': 4, 'complete': 5, 'educational': 6, 'frameworks': 7, 'free': 8, 'gemini': 9, 'generation': 10, 'goal': 11, 'integration': 12, 'it': 13, 'just': 14, 'only': 15, 'pdf': 16, 'productivity': 17, 'smart': 18, 'tool': 19, 'try': 20, 'using': 21, 'based': 22, 'bit': 23, 'but': 24, 'clicker': 25, 'created': 26, 'crypto': 27, 'enjoy': 28, 'for': 29, 'game': 30, 'i': 31, 'its': 32, 'may': 33, 'maybe': 34, 'me': 35, 'my': 36, 'not': 37, 'of': 38, 'play': 39, 'practice': 40, 'run': 41, 'small': 42, 'some': 43, 'to': 44, 'twitter': 45, 'usual': 46, 'utility': 47, 'vibecode': 48, 'was': 49, 'you': 50, 'squad': 51, 'with': 52, 'all': 53, 'and': 54, 'autonomous': 55, 'beach': 56, 'building': 57, 'business': 58, 'can': 59, 'cant': 60, 'collect': 61, 'exciting': 62, 'full': 63, 'fully': 64, 'future': 65, 'idea': 66, 'im': 67, 'in': 68, 'income': 69, 'itself': 70, 'looks': 71, 'on': 72, 'relaxing': 73, 'runs': 74, 'say': 75, 'share': 76, 'so': 77, 'that': 78, 'this': 79, 'today': 80, 'tomorrow': 81, 'while': 82, 'yet': 83, 'app': 84, 'been': 85, 'big': 86, 'businesses': 87, 'career': 88, 'challenge': 89, 'do': 90, 'dollars': 91, 'generated': 92, 'if': 93, 'ive': 94, 'kinda': 95, 'marketed': 96, 'marketing': 97, 'millions': 98, 'never': 99, 'own': 100, 'product': 101, 'reason': 102, 'roles': 103, 'see': 104, 'shipped': 105, 'thousands': 106, 'users': 107, 'views': 108, 'wanna': 109, 'want': 110, 'whole': 111, 'about': 112, 'article': 113, 'exchange': 114, 'from': 115, 'private': 116, 're': 117, 'ai': 118, 'apps': 119, 'become': 120, 'builders': 121, 'contracts': 122, 'create': 123, 'ecosystems': 124, 'effortlessly': 125, 'home': 126, 'launching': 127, 'like': 128, 'onchain': 129, 'plena': 130, 'power': 131, 'products': 132, 'soon': 133, 'supercharge': 134, 'trading': 135, 'unleashing': 136, 'value': 137, 'were': 138, 'who': 139, 'will': 140, 'am': 141, 'an': 142, 'anything': 143, 'basic': 144, 'basically': 145, 'build': 146, 'clone': 147, 'code': 148, 'community': 149, 'configure': 150, 'considered': 151, 'databases': 152, 'infra': 153, 'is': 154, 'knowledge': 155, 'last': 156, 'level': 157, 'night': 158, 'non': 159, 'repo': 160, 'right': 161, 'servers': 162, 'specific': 163, 'sure': 164, 'tech': 165, 'x': 166, 'allin': 167, 'are': 168, 'experiences': 169, 'goes': 170, 'horizon': 171, 'mature': 172, 'openai': 173, 'says': 174, 'hello': 175, 'rainy': 176, 'coding': 177, 'punk': 178, 'rock': 179, 'good': 180, 'pcb': 181, 'surprisingly': 182, 'back': 183, 'enough': 184, 'shitposting': 185, 'slop': 186, 'after': 187, 'concept': 188, 'definitely': 189, 'development': 190, 'did': 191, 'got': 192, 'new': 193, 'tasks': 194, 'weve': 195, 'y': 196, 'your': 197, 'be': 198, 'no': 199, 'nowadays': 200, 'release': 201, 'there': 202, 'vibe': 203, 'water': 204, 'when': 205, 'adopt': 206, 'at': 207, 'awesome': 208, 'blocks': 209, 'crosschain': 210, 'dapp': 211, 'developers': 212, 'fragmented': 213, 'hard': 214, 'integrate': 215, 'into': 216, 'opensource': 217, 'our': 218, 'sdk': 219, 'should': 220, 'standard': 221, 'still': 222, 'unified': 223, 'we': 224, 'aspire': 225, 'boring': 226, 'day': 227, 'important': 228, 'life': 229, 'lose': 230, 'many': 231, 'people': 232, 'settle': 233, 'simply': 234, 'someone': 235, 'spark': 236, 'their': 237, 'aapl': 238, 'gradients': 239, 'msft': 240, 'price': 241, 'stock': 242, 'yr': 243, 'analysis': 244, 'answers': 245, 'best': 246, 'better': 247, 'cheat': 248, 'claude': 249, 'emails': 250, 'engineering': 251, 'formatting': 252, 'goat': 253, 'grok': 254, 'llm': 255, 'math': 256, 'reasoning': 257, 'sheet': 258, 'social': 259, 'sucks': 260, 'topics': 261, 'turbo': 262, 'agents': 263, 'approach': 264, 'catch': 265, 'cure': 266, 'dont': 267, 'framework': 268, 'hangover': 269, 'learn': 270, 'maintainable': 271, 'miss': 272, 'much': 273, 'pretty': 274, 'requirements': 275, 'software': 276, 'systematic': 277, 'talk': 278, 'week': 279, 'distribute': 280, 'as': 281, 'develop': 282, 'different': 283, 'else': 284, 'go': 285, 'long': 286, 'or': 287, 'programming': 288, 'prototype': 289, 'result': 290, 'something': 291, 'test': 292, 'they': 293, 'things': 294, 'thinking': 295, 'use': 296, 'works': 297, 'courses': 298, 'ct': 299, 'english': 300, 'focus': 301, 'frens': 302, 'heres': 303, 'input': 304, 'make': 305, 'more': 306, 'now': 307, 'output': 308, 'plan': 309, 'posts': 310, 'prediction': 311, 'refining': 312, 'strategy': 313, 'up': 314, 'whats': 315, 'win': 316, 'deep': 317, 'happy': 318, 'hours': 319, 'report': 320, 'database': 321, 'decided': 322, 'feature': 323, 'first': 324, 'happened': 325, 'have': 326, 'how': 327, 'interpret': 328, 'messages': 329, 'routine': 330, 'saved': 331, 'speed': 332, 'version': 333, 'way': 334, 'by': 335, 'made': 336, 'programmers': 337, 'fixes': 338, 'guy': 339, 'love': 340, 'unreal': 341, 'automations': 342, 'browser': 343, 'kernel': 344, 'mcps': 345, 'pbj': 346, 'actually': 347, 'africa': 348, 'amount': 349, 'bug': 350, 'electricity': 351, 'few': 352, 'fix': 353, 'insane': 354, 'most': 355, 'probably': 356, 'same': 357, 'session': 358, 'supervised': 359, 'used': 360, 'village': 361, 'worked': 362, 'able': 363, 'anymore': 364, 'anyone': 365, 'before': 366, 'cuz': 367, 'every': 368, 'find': 369, 'innovation': 370, 'joking': 371, 'months': 372, 'nothing': 373, 'one': 374, 'ppl': 375, 'since': 376, 'stop': 377, 'strange': 378, 'supposedly': 379, 'switched': 380, 'why': 381, 'ever': 382, 'fastest': 383, 'growing': 384, 'startup': 385, 'swedish': 386, 'turned': 387, 'unicorn': 388, 'bullish': 389, 'holy': 390, 'million': 391, 'really': 392, 'world': 393, 'faster': 394, 'founders': 395, 'solo': 396, 'step': 397, 'workflow': 398, 'arriving': 399, 'diagrams': 400, 'end': 401, 'fun': 402, 'less': 403, 'nicer': 404, 'specs': 405, 'text': 406, 'than': 407, 'walls': 408, 'around': 409, 'button': 410, 'buy': 411, 'fuck': 412, 'give': 413, 'guess': 414, 'he': 415, 'hey': 416, 'himself': 417, 'ill': 418, 'logo': 419, 'mad': 420, 'pay': 421, 'said': 422, 'unclear': 423, 'wed': 424, 'cleanup': 425, 'efficiency': 426, 'emerging': 427, 'gaining': 428, 'initial': 429, 'loose': 430, 'needs': 431, 'often': 432, 'polishing': 433, 'prompts': 434, 'refine': 435, 'role': 436, 'specialist': 437, 'stability': 438, 'stems': 439, 'tools': 440, 'traction': 441, 'vibecodingusing': 442, 'where': 443, 'which': 444, 'changes': 445, 'connected': 446, 'feedback': 447, 'friends': 448, 'games': 449, 'live': 450, 'multiplayer': 451, 'phone': 452, 'realtime': 453, 'testing': 454, 'thanks': 455, 'again': 456, 'attempts': 457, 'blessing': 458, 'complexity': 459, 'due': 460, 'gotta': 461, 'hour': 462, 'launch': 463, 'numerous': 464, 'over': 465, 'project': 466, 'put': 467, 'sat': 468, 'scratch': 469, 'starting': 470, 'stuff': 471, 'then': 472, 'through': 473, 'took': 474, 'videos': 475, 'work': 476, 'youtube': 477, 'abstract': 478, 'barrier': 479, 'completely': 480, 'couple': 481, 'dev': 482, 'engineers': 483, 'entry': 484, 'era': 485, 'etc': 486, 'get': 487, 'kyear': 488, 'out': 489, 'payment': 490, 'perfect': 491, 'place': 492, 'platforms': 493, 'removed': 494, 'start': 495, 'whop': 496, 'cursor': 497, 'h': 498, 'looking': 499, 'mins': 500, 'nextjs': 501, 'personal': 502, 'photos': 503, 'projects': 504, 'prompting': 505, 'rebuilt': 506, 'remember': 507, 'site': 508, 'spent': 509, 'sunday': 510, 'template': 511, 'time': 512, 'trying': 513, 'arent': 514, 'because': 515, 'cool': 516, 'discord': 517, 'farcade': 518, 'follow': 519, 'following': 520, 'look': 521, 'missing': 522, 'once': 523, 'team': 524, 'them': 525, 'think': 526, 'timeline': 527, 'very': 528, 'youre': 529, 'comeback': 530, 'common': 531, 'converging': 532, 'coverage': 533, 'downsides': 534, 'efficient': 535, 'has': 536, 'managed': 537, 'meta': 538, 'obviously': 539, 'patterns': 540, 'poorly': 541, 'severe': 542, 'shift': 543, 'too': 544, 'toward': 545, 'ways': 546, 'weaknesses': 547, 'console': 548, 'please': 549, 'call': 550, 'wakeup': 551, 'af': 552, 'bearish': 553, 'changer': 554, 'communities': 555, 'connecting': 556, 'developing': 557, 'flow': 558, 'gm': 559, 'grow': 560, 'his': 561, 'opportunities': 562, 'streaming': 563, 'top': 564, 'builtin': 565, 'chatgpt': 566, 'clear': 567, 'defined': 568, 'gambling': 569, 'hoping': 570, 'loop': 571, 'magic': 572, 'mockups': 573, 'outcome': 574, 'ready': 575, 'real': 576, 'references': 577, 'stack': 578, 'thats': 579, 'throwing': 580, 'tied': 581, 'creative': 582, 'deploy': 583, 'eaten': 584, 'getting': 585, 'honestly': 586, 'next': 587, 'nobody': 588, 'replit': 589, 'safe': 590, 'video': 591, 'viral': 592, 'went': 593, 'doomed': 594, 'spiral': 595, 'wife': 596, 'backed': 597, 'capital': 598, 'cofounders': 599, 'combinator': 600, 'corporate': 601, 'devos': 602, 'funding': 603, 'm': 604, 'round': 605, 'secure': 606, 'seed': 607, 'structures': 608, 'vybe': 609, 'also': 610, 'bet': 611, 'codexero': 612, 'complex': 613, 'lets': 614, 'lock': 615, 'message': 616, 'myself': 617, 'note': 618, 'others': 619, 'point': 620, 'pushing': 621, 'sound': 622, 'claudes': 623, 'cute': 624, 'done': 625, 'furious': 626, 'know': 627, 'loves': 628, 'suggesting': 629, 'take': 630, 'weekend': 631, 'dapps': 632, 'deploys': 633, 'everything': 634, 'experiments': 635, 'fast': 636, 'gcode': 637, 'ideas': 638, 'meets': 639, 'offchain': 640, 'position': 641, 'production': 642, 'quickly': 643, 'rack': 644, 'rewards': 645, 'sei': 646, 'ship': 647, 'tge': 648, 'turn': 649, 'xp': 650, 'boys': 651, 'called': 652, 'gonna': 653, 'movie': 654, 'propaganda': 655, 'pure': 656, 'state': 657, 'todays': 658, 'beginning': 659, 'advice': 660, 'andrej': 661, 'bill': 662, 'gates': 663, 'hire': 664, 'karpathy': 665, 'lazy': 666, 'upgraded': 667, 'aidriven': 668, 'announcement': 669, 'applications': 670, 'creators': 671, 'empowering': 672, 'excited': 673, 'infrastructure': 674, 'intelligent': 675, 'partner': 676, 'partnership': 677, 'programmable': 678, 'pvpfun': 679, 'turning': 680, 'web': 681, 'architecture': 682, 'comparison': 683, 'config': 684, 'default': 685, 'difference': 686, 'file': 687, 'isnt': 688, 'prompt': 689, 'ran': 690, 'settings': 691, 'twice': 692, 'ui': 693, 'vanilla': 694, 'watch': 695, 'apis': 696, 'dealing': 697, 'everyone': 698, 'finally': 699, 'hair': 700, 'platform': 701, 'puller': 702, 'peace': 703, 'safely': 704, 'stay': 705, 'came': 706, 'june': 707, 'store': 708, 'th': 709, 'honest': 710, 'u': 711, 'afraid': 712, 'amazing': 713, 'checkpoint': 714, 'gt': 715, 'alpha': 716, 'announcements': 717, 'dropped': 718, 'further': 719, 'mint': 720, 'space': 721, 'special': 722, 'stick': 723, 'tight': 724, 'tuned': 725, 'whitelist': 726, 'wl': 727, 'would': 728, 'xero': 729, 'ok': 730, 'super': 731, 'id': 732, 'memory': 733, 'regrets': 734, 'save': 735, 'todo': 736, 'wallet': 737, 'woke': 738, 'does': 739, 'learned': 740, 'min': 741, 'nano': 742, 'plain': 743, 'rough': 744, 'scribble': 745, 'sketch': 746, 'studio': 747, 'true': 748, 'type': 749, 'what': 750, 'analog': 751, 'april': 752, 'born': 753, 'far': 754, 'feb': 755, 'lessons': 756, 'march': 757, 'modular': 758, 'mrr': 759, 'recruited': 760, 'us': 761, 'handing': 762, 'heard': 763, 'helped': 764, 'lovable': 765, 'other': 766, 'solid': 767, 'technical': 768, 'anywhere': 769, 'laptop': 770, 'mobile': 771, 'need': 772, 'stage': 773, 'unlocked': 774, 'via': 775, 'canceling': 776, 'dates': 777, 'meetings': 778, 'reply': 779, 'saas': 780, 'brutal': 781, 'channel': 782, 'clearly': 783, 'communicated': 784, 'founder': 785, 'him': 786, 'indian': 787, 'israeli': 788, 'lot': 789, 'needed': 790, 'skin': 791, 'spoke': 792, 'thin': 793, 'wanted': 794, 'yesterday': 795, 'amp': 796, 'animated': 797, 'could': 798, 'effects': 799, 'lighting': 800, 'liquid': 801, 'living': 802, 'metal': 803, 'physics': 804, 'pomodoro': 805, 'ring': 806, 'splits': 807, 'svg': 808, 'timer': 809, 'turns': 810, 'vibecoded': 811, 'visual': 812, 'dangers': 813, 'discussing': 814, 'without': 815, 'days': 816, 'impressive': 817, 'shocked': 818, 'useful': 819, 'figma': 820, 'outie': 821, 'skip': 822, 'straight': 823, 'thinks': 824, 'bloodline': 825, 'entire': 826, 'retiring': 827, 'department': 828, 'f': 829, 'faces': 830, 'hyper': 831, 'niche': 832, 'problem': 833, 'solution': 834, 'solves': 835, 'times': 836, 'drop': 837, 'easily': 838, 'farm': 839, 'hit': 840, 'hope': 841, 'jackpot': 842, 'month': 843, 'objective': 844, 'season': 845, 'weeks': 846, 'within': 847, 'btw': 848, 'failure': 849, 'rest': 850, 'ya': 851, 'invented': 852, 'well': 853, 'bugs': 854, 'companion': 855, 'fixing': 856, 'hands': 857, 'hobby': 858, 'invaluable': 859, 'mainly': 860, 'manus': 861, 'occasionally': 862, 'reading': 863, 'research': 864, 'sees': 865, 'study': 866, 'tbh': 867, 'though': 868, 'verbose': 869, 'writes': 870, 'abs': 871, 'brake': 872, 'controls': 873, 'check': 874, 'star': 875, 'asylum': 876, 'both': 877, 'codes': 878, 'great': 879, 'had': 880, 'here': 881, 'locked': 882, 'multiple': 883, 'sign': 884, 'st': 885, 'timers': 886, 'vibing': 887, 'agencies': 888, 'artificial': 889, 'being': 890, 'biggest': 891, 'chain': 892, 'directly': 893, 'enter': 894, 'especially': 895, 'established': 896, 'gave': 897, 'history': 898, 'intelligence': 899, 'logic': 900, 'longer': 901, 'obstacle': 902, 'question': 903, 'revolutionary': 904, 'teams': 905, 'transfer': 906, 'cons': 907, 'evening': 908, 'pros': 909, 'thank': 910, 'topic': 911, 'votes': 912, 'actual': 913, 'any': 914, 'asking': 915, 'boilerplates': 916, 'friend': 917, 'instead': 918, 'job': 919, 'remote': 920, 'writing': 921, 'phd': 922, 'running': 923, 'allow': 924, 'between': 925, 'devs': 926, 'gone': 927, 'google': 928, 'hes': 929, 'incredible': 930, 'indie': 931, 'jam': 932, 'marty': 933, 'portal': 934, 'travel': 935, 'complicated': 936, 'difficult': 937, 'economy': 938, 'education': 939, 'max': 940, 'possible': 941, 'profit': 942, 'those': 943, 'trends': 944, 'two': 945, 'bi': 946, 'chilling': 947, 'picking': 948, 'waiting': 949, 'winner': 950, 'winners': 951, 'believe': 952, 'details': 953, 'endtoend': 954, 'genuinely': 955, 'implementation': 956, 'touching': 957, 'add': 958, 'autonomously': 959, 'cases': 960, 'coders': 961, 'context': 962, 'debugging': 963, 'edge': 964, 'eg': 965, 'eliminate': 966, 'enhance': 967, 'expand': 968, 'expert': 969, 'handle': 970, 'loops': 971, 'modellevel': 972, 'multistep': 973, 'must': 974, 'problems': 975, 'specialized': 976, 'windows': 977, 'against': 978, 'crappy': 979, 'deserves': 980, 'forever': 981, 'managing': 982, 'outcomes': 983, 'post': 984, 'themselves': 985, 'towards': 986, 'brought': 987, 'engineer': 988, 'makes': 989, 'remotely': 990, 'tmux': 991, 'worse': 992, 'collaborative': 993, 'pair': 994, 'pairing': 995, 'drinking': 996, 'fav': 997, 'unlimited': 998, 'anime': 999, 'enhanced': 1000, 'framer': 1001, 'landing': 1002, 'motion': 1003, 'nostalgic': 1004, 'page': 1005, 'theme': 1006, 'threejs': 1007, 'tribe': 1008, 'warm': 1009, 'website': 1010, 'wholesome': 1011, 'coin': 1012, 'generative': 1013, 'sides': 1014, 'almost': 1015, 'combination': 1016, 'come': 1017, 'creations': 1018, 'direction': 1019, 'editors': 1020, 'interfaces': 1021, 'linked': 1022, 'media': 1023, 'models': 1024, 'poe': 1025, 'quizzes': 1026, 'thread': 1027, 'workflows': 1028, 'comes': 1029, 'managers': 1030, 'prototypes': 1031, 'show': 1032, 'tell': 1033, 'zuckerberg': 1034, 'agent': 1035, 'changing': 1036, 'down': 1037, 'line': 1038, 'senior': 1039, 'sits': 1040, 'draft': 1041, 'equivalent': 1042, 'imagine': 1043, 'old': 1044, 'rn': 1045, 'single': 1046, 'slur': 1047, 'breaking': 1048, 'certain': 1049, 'graph': 1050, 'introducing': 1051, 'represents': 1052, 'setting': 1053, 'starts': 1054, 'structure': 1055, 'tried': 1056, 'food': 1057, 'ma': 1058, 'discussed': 1059, 'discussion': 1060, 'essay': 1061, 'interesting': 1062, 'link': 1063, 'automatically': 1064, 'checks': 1065, 'commit': 1066, 'github': 1067, 'issues': 1068, 'little': 1069, 'potential': 1070, 'presenting': 1071, 'pushed': 1072, 'safer': 1073, 'security': 1074, 'skill': 1075, 'vibecheck': 1076, 'elon': 1077, 'fire': 1078, 'staff': 1079, '𝕏': 1080, 'brands': 1081, 'distribution': 1082, 'harder': 1083, 'higher': 1084, 'keep': 1085, 'means': 1086, 'pressure': 1087, 'revenue': 1088, 'shipping': 1089, 'stand': 1090, 'upside': 1091, 'ux': 1092, 'weak': 1093, 'along': 1094, 'brain': 1095, 'break': 1096, 'innovations': 1097, 'solutions': 1098, 'during': 1099, 'hub': 1100, 'redesign': 1101, 'showcased': 1102, 'submission': 1103, 'talus': 1104, 'workshop': 1105, 'guys': 1106, 'plz': 1107, 'apart': 1108, 'auth': 1109, 'builder': 1110, 'fall': 1111, 'hosting': 1112, 'login': 1113, 'nocode': 1114, 'payments': 1115, 'realworld': 1116, 'set': 1117, 'until': 1118, 'working': 1119, 'bad': 1120, 'cloudfare': 1121, 'hired': 1122, 'js': 1123, 'practices': 1124, 'services': 1125, 'another': 1126, 'creator': 1127, 'dex': 1128, 'happening': 1129, 'memecoin': 1130, 'powerful': 1131, 'quietly': 1132, 'rise': 1133, 'rush': 1134, 'tokenize': 1135, 'wildest': 1136, 'apple': 1137, 'review': 1138, 'healthcare': 1139, 'latinos': 1140, 'cost': 1141, 'interest': 1142, 'money': 1143, 'nope': 1144, 'oh': 1145, 'told': 1146, 'wow': 1147, 'making': 1148, 'companies': 1149, 'finance': 1150, 'fintech': 1151, 'having': 1152, 'mbas': 1153, 'none': 1154, 'requisite': 1155, 'tables': 1156, 'alone': 1157, 'application': 1158, 'configs': 1159, 'enterprise': 1160, 'entirely': 1161, 'intense': 1162, 'might': 1163, 'otherwise': 1164, 'required': 1165, 'talks': 1166, 'thing': 1167, 'trusting': 1168, 'wont': 1169, 'america': 1170, 'deck': 1171, 'pitch': 1172, 'raised': 1173, 'read': 1174, 'these': 1175, 'date': 1176, 'entering': 1177, 'event': 1178, 'grabs': 1179, 'planet': 1180, 'proud': 1181, 'thousand': 1182, 'town': 1183, 'contract': 1184, 'easy': 1185, 'fund': 1186, 'funded': 1187, 'interact': 1188, 'wallets': 1189, 'continue': 1190, 'let': 1191, 'pc': 1192, 'portfolio': 1193, 'wants': 1194, 'always': 1195, 'buttons': 1196, 'classic': 1197, 'click': 1198, 'corrections': 1199, 'display': 1200, 'haha': 1201, 'nice': 1202, 'term': 1203, 'algorithms': 1204, 'doesnt': 1205, 'frequency': 1206, 'high': 1207, 'apply': 1208, 'background': 1209, 'branch': 1210, 'chat': 1211, 'control': 1212, 'desktop': 1213, 'diffs': 1214, 'later': 1215, 'mode': 1216, 'parallel': 1217, 'sessions': 1218, 'tackle': 1219, 'toilet': 1220, 'vm': 1221, 'vms': 1222, 'voice': 1223, 'ask': 1224, 'combine': 1225, 'lol': 1226, 'three': 1227, 'cash': 1228, 'd': 1229, 'extraction': 1230, 'favorite': 1231, 'levels': 1232, 'simulator': 1233, 'vc': 1234, 'bb': 1235, 'christmas': 1236, 'serious': 1237, 'afternoon': 1238, 'costs': 1239, 'director': 1240, 'friday': 1241, 'lab': 1242, 'pocket': 1243, 'rant': 1244, 'unhinged': 1245, 'v': 1246, 'walk': 1247, 'wine': 1248, 'fucking': 1249, 'ios': 1250, 'macos': 1251, 'sonnet': 1252, 'asynchronous': 1253, 'cooking': 1254, 'early': 1255, 'experience': 1256, 'jobs': 1257, 'keeping': 1258, 'list': 1259, 'parallelized': 1260, 'reminds': 1261, 'results': 1262, 'spinning': 1263, 'strongly': 1264, 'task': 1265, 'confidence': 1266, 'grant': 1267, 'knows': 1268, 'lord': 1269, 'agency': 1270, 'crm': 1271, 'going': 1272, 'past': 1273, 'recruiting': 1274, 'terrible': 1275, 'years': 1276, 'coming': 1277, 'jeet': 1278, 'recommend': 1279, 'given': 1280, 'opposite': 1281, 'ownership': 1282, 'rather': 1283, 'responsibility': 1284, 'taking': 1285, 'adding': 1286, 'becoming': 1287, 'codebase': 1288, 'git': 1289, 'learning': 1290, 'scared': 1291, 'tells': 1292, 'wrong': 1293, 'glasses': 1294, 'god': 1295, 'spec': 1296, 'vs': 1297, 'actions': 1298, 'banking': 1299, 'consequences': 1300, 'face': 1301, 'legal': 1302, 'box': 1303, 'burn': 1304, 'concrete': 1305, 'cron': 1306, 'discovering': 1307, 'example': 1308, 'fumble': 1309, 'larp': 1310, 'provide': 1311, 'seen': 1312, 'tokens': 1313, 'lady': 1314, 'yes': 1315, 'asked': 1316, 'cc': 1317, 'convinced': 1318, 'demonstration': 1319, 'effect': 1320, 'generate': 1321, 'generates': 1322, 'ho

In [13]:
import top2vec
print(top2vec.__version__)

1.0.36

In [14]:
top2vec_model = Top2Vec(
    documents=documents,
    contextual_top2vec=True,
    ngram_vocab=True,
    min_count=10,
    embedding_model='all-MiniLM-L6-v2',    
    speed='learn',
    workers=2,
    keep_documents=True,
    verbose=True,
 )

topic_words, topic_word_scores, topic_nums = top2vec_model.get_topics()

2026-04-12 15:14:31,480 - top2vec - INFO - Pre-processing documents for training
2026-04-12 15:14:33,069 - top2vec - INFO - Creating vocabulary embedding
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6370.66it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Embedding vocabulary: 100%|██████████| 41/41 [00:04<00:00,  8.66it/s]
2026-04-12 15:14:41,139 - top2vec - INFO - Create contextualized document embeddings
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6355.29it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Embedding documents: 100%|██████████| 641/641 [01:19<00:00,  8.03it/s]
20511it [00:00, 50820.30it/s]
2026-04-12 15:17:49,098 - top2vec - INFO - Creating lower dimension embedding of documents
2026-04-12 15:18:13,484 - top2vec - INFO - Finding dense areas of documents
2026-04-12 15:18:16,889 - top2vec - INFO - Finding topics
Smoothing document token embeddings: 100%|██████████| 20511/20511 [00:07<00:00, 2774.75it/s]
Calculating document topic distributions: 100%|██████████| 20511/20511 [00:03<00:00, 5989.85it/s]

In [15]:
topic_sizes, topic_ids = top2vec_model.get_topic_sizes()
pd.DataFrame({
    "topic_id": topic_ids,
    "size": topic_sizes
}).sort_values("size", ascending=False).head(10)

   topic_id    size
0         1  671700
1         0    8093

In [16]:
print(len(topic_sizes))

2

In [17]:
# Coherence metrics for Top2Vec topics (C_V and NPMI)
topic_pairs = []
for topic_num, topic in zip(topic_nums, topic_words):
    cleaned_topic_terms = []
    for term in topic[:10]:
        # ngram terms like "vibe coding" are split so they can be matched to dictionary tokens
        for tok in str(term).split():
            if tok in dictionary.token2id:
                cleaned_topic_terms.append(tok)
    # keep token order, drop duplicates
    cleaned_topic_terms = list(dict.fromkeys(cleaned_topic_terms))
    if len(cleaned_topic_terms) >= 2:
        topic_pairs.append((topic_num, cleaned_topic_terms))

topics_for_coherence = [words for _, words in topic_pairs]
topic_nums_for_coherence = [topic_num for topic_num, _ in topic_pairs]

if not topics_for_coherence:
    raise ValueError("No valid topics left for coherence calculation. Try lowering dictionary filtering or increasing topic words.")

coherence_cv_model = CoherenceModel(
    topics=topics_for_coherence,
    texts=tokenized_documents,
    dictionary=dictionary,
    coherence='c_v',
)

coherence_npmi_model = CoherenceModel(
    topics=topics_for_coherence,
    texts=tokenized_documents,
    dictionary=dictionary,
    coherence='c_npmi',
)

coherence_cv = coherence_cv_model.get_coherence()
coherence_npmi = coherence_npmi_model.get_coherence()

print(f"Total topics used for coherence: {len(topics_for_coherence)}")
print(f"C_V coherence: {coherence_cv:.4f}")
print(f"NPMI coherence: {coherence_npmi:.4f}")

topic_coherence = pd.DataFrame({
    'topic_num': topic_nums_for_coherence,
    'topic_words': [' '.join(words) for words in topics_for_coherence],
    'c_v': coherence_cv_model.get_coherence_per_topic(),
    'npmi': coherence_npmi_model.get_coherence_per_topic(),
})

topic_coherence.sort_values('c_v', ascending=False).head(10)

Total topics used for coherence: 2
C_V coherence: 0.4163
NPMI coherence: -0.2312

,topic_num,topic_words,c_v,npmi
0,0,dance clubfor vibe designing marketing vibecod...,0.460333,-0.267261
1,1,vibe debugging marketing engineering designing...,0.372224,-0.195152

In [26]:
# get all topic words values
topic_words_values = topic_coherence.sort_values('c_v', ascending=False).head(10)['topic_words'].values
print(topic_words_values)

['dance clubfor vibe designing marketing vibecoded projects investing vibecode camp punk rock engineering living debugging'
 'vibe debugging marketing engineering designing vibecoded projects investing vibecode cleanup ltcodinggt camp living']

In [18]:
# Save model
top2vec_model.save("top2vec_contextual_ngram_c10.model")

# Load model (di masa depan)
# from top2vec import Top2Vec
top2vec_model = Top2Vec.load("top2vec_contextual_ngram_c10.model")



# Load di kemudian hari
# embeddings = np.load("top2vec_contextual_ngram_c10_embeddings.npy")


# Simpan Dictionary
dictionary.save("top2vec_contextual_ngram_c10.dict")

# Simpan tokenized_documents (menggunakan pickle karena list of lists)
import pickle
with open("top2vec_contextual_ngram_c10_tokenized_docs.pkl", "wb") as f:
    pickle.dump(tokenized_documents, f)
    
    
    
# Simpan ringkasan topik dan metriknya
topic_coherence.to_csv("top2vec_contextual_ngram_c10_metrics_summary.csv", index=False)

# Simpan representasi topik (10 kata teratas)
top_words_df = pd.DataFrame(topic_words)
top_words_df.to_csv("top2vec_contextual_ngram_c10_topic_words.csv", index=False)