In [1]:
!pip install deep_translator

Collecting deep_translator
  Downloading deep_translator-1.11.4-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in /usr/local/lib/python3.12/dist-packages (from deep_translator) (4.13.5)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in /usr/local/lib/python3.12/dist-packages (from deep_translator) (2.32.4)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep_translator) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep_translator) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep_translator) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep_translator) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep_translator) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep_translator) (2026.2.25)
Downloading deep_translator-1.11.4-py3-none-any.whl (42 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 kB 4.7 MB/s eta 0:00:00
Installing collected packages: deep_translator
Successfully installed deep_translator-1.11.4

In [2]:
import pandas as pd
from deep_translator import GoogleTranslator

In [3]:
ds = pd.read_csv("/content/vibe_coding_all_combined.csv")

In [4]:
ds

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1886192184808149383,2025-02-02 23:22:18+00:00,444,@karpathy me vibe coding and hope it can just ...,1886193454730137763,https://pbs.twimg.com/media/Gi0a82HaQAA97Q-.jpg,karpathy,en,NaN,0,5,10,https://x.com/Yuchenj_UW/status/18861934547301...,800854096219471872,Yuchenj_UW
1,1886196686709805486,2025-02-02 23:35:08+00:00,10,vibes capital meets vibe coding = greatest eco...,1886196686709805486,NaN,NaN,en,NaN,0,0,0,https://x.com/nikunj/status/1886196686709805486,30405893,nikunj
2,1886198988199600391,2025-02-02 23:44:17+00:00,3563,vibe coding https://t.co/1hHVMmunrw,1886198988199600391,https://pbs.twimg.com/media/Gi0f9fAWgAAgox6.jpg,NaN,en,NaN,18,35,191,https://x.com/IterIntellectus/status/188619898...,1655936149733654530,IterIntellectus
3,1886203668619493715,2025-02-03 00:02:53+00:00,0,can attest. vibe coding is hella fun and borde...,1886203668619493715,NaN,NaN,en,NaN,0,0,0,https://x.com/kermankohli/status/1886203668619...,143624329,kermankohli
4,1886204681766027415,2025-02-03 00:06:54+00:00,7,I have built a few app ideas in my spare time ...,1886204681766027415,NaN,NaN,en,NaN,0,0,0,https://x.com/luizfgparreira/status/1886204681...,2937425254,luizfgparreira
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21392,2027533407245521272,2026-02-27 23:56:48+00:00,173,If you worried that everyone in the future wil...,2027533407245521272,NaN,NaN,en,NaN,2,25,5,https://x.com/neogoose_btw/status/202753340724...,1018840293901328384,neogoose_btw
21393,2027533580868395390,2026-02-27 23:57:30+00:00,223,I wonder if Claude does a better job vibe codi...,2027533580868395390,NaN,NaN,en,NaN,3,10,7,https://x.com/deanwball/status/202753358086839...,30557408,deanwball
21394,2027533965628707209,2026-02-27 23:59:01+00:00,1,"Hablando de Vibe Coding, en lugar de meter IA ...",2027533965628707209,NaN,NaN,es,NaN,0,1,0,https://x.com/diegofesc/status/202753396562870...,90892581,diegofesc
21395,2027534089402913067,2026-02-27 23:59:31+00:00,725,Everyone is talking about the death of consume...,2027534089402913067,https://pbs.twimg.com/media/HCM5MvQbEAIgm2o.png,NaN,en,NaN,6,58,73,https://x.com/omooretweets/status/202753408940...,1399771783415308291,omooretweets
21396,2027534141638541485,2026-02-27 23:59:43+00:00,5,Vibe coding https://t.co/PlJzlrLZDl,2027534141638541485,https://pbs.twimg.com/media/HCM_jQ2bEAMUL9r.png,NaN,en,NaN,0,0,0,https://x.com/Mubarratc/status/202753414163854...,1637046123037597696,Mubarratc

In [6]:
#get count of all text which are not en language
ds[ds['lang'] != 'en'].count()

conversation_id_str        2167
created_at                 2167
favorite_count             2167
full_text                  2167
id_str                     2167
image_url                   691
in_reply_to_screen_name      34
lang                       2167
location                      0
quote_count                2167
reply_count                2167
retweet_count              2167
tweet_url                  2167
user_id_str                2167
username                   2167
dtype: int64

In [7]:
translator = GoogleTranslator(source='auto', target='en')

In [8]:
ds['full_text_translated'] = ds.apply(lambda row: translator.translate(row['full_text']) if row['lang'] != 'en' else row['full_text'], axis=1)

In [10]:
#save new ds
ds.to_csv("/content/vibe_coding_combined_translated.csv", index=False)